
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 31 2019 19:26:50 IST (Oct 31 2019 13:56:50 UTC)

// Verification Directory fv/rad4fft 

module rad4fft(a, b, c, d, A, Ai, B, Bi, C, Ci, D, Di);
  input [3:0] a, b, c, d;
  output [5:0] A, Ai, B, Bi, C, Ci, D, Di;
  wire [3:0] a, b, c, d;
  wire [5:0] A, Ai, B, Bi, C, Ci, D, Di;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_47, n_48, n_49, n_51, n_53, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_83, n_84, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_102;
  wire n_103, n_108, n_110, n_113, n_115, n_116, n_118, n_119;
  wire n_120, n_150, n_151, n_153, n_154;
  assign Di[0] = Bi[0];
  assign Di[4] = Di[5];
  assign D[0] = B[0];
  assign D[1] = B[1];
  assign D[2] = B[2];
  assign D[3] = B[3];
  assign D[4] = B[5];
  assign D[5] = B[5];
  assign Ci[0] = 1'b0;
  assign Ci[1] = 1'b0;
  assign Ci[2] = 1'b0;
  assign Ci[3] = 1'b0;
  assign Ci[4] = 1'b0;
  assign Ci[5] = 1'b0;
  assign C[0] = A[0];
  assign Bi[4] = Bi[5];
  assign B[4] = B[5];
  assign Ai[0] = 1'b0;
  assign Ai[1] = 1'b0;
  assign Ai[2] = 1'b0;
  assign Ai[3] = 1'b0;
  assign Ai[4] = 1'b0;
  assign Ai[5] = 1'b0;
  ADDFXL g2549(.A (n_21), .B (n_92), .CI (n_113), .CO (A[5]), .S
       (A[4]));
  OAI21XL g2545(.A0 (n_118), .A1 (n_119), .B0 (n_120), .Y (C[4]));
  NAND2XL g2546(.A (n_119), .B (n_118), .Y (n_120));
  OAI22XL g2548(.A0 (n_115), .A1 (n_93), .B0 (n_116), .B1 (n_26), .Y
       (C[5]));
  CLKXOR2X1 g2547(.A (n_116), .B (n_115), .Y (n_118));
  ADDFX1 g2551(.A (n_150), .B (n_81), .CI (n_110), .CO (n_113), .S
       (A[3]));
  ADDFX1 g2550(.A (n_94), .B (n_84), .CI (n_108), .CO (n_115), .S
       (C[3]));
  ADDFX1 g2553(.A (n_99), .B (n_59), .CI (n_98), .CO (n_110), .S
       (A[2]));
  ADDFX1 g2552(.A (n_100), .B (n_32), .CI (n_88), .CO (n_108), .S
       (C[2]));
  MXI2XL g2554(.A (n_20), .B (c[3]), .S0 (n_97), .Y (B[3]));
  OAI2BB1XL g2555(.A0N (c[3]), .A1N (n_96), .B0 (n_95), .Y (B[5]));
  ADDFX1 g2556(.A (n_39), .B (n_53), .CI (n_41), .CO (n_100), .S
       (C[1]));
  OAI21XL g2577(.A0 (n_89), .A1 (n_103), .B0 (n_90), .Y (n_99));
  OAI21XL g2563(.A0 (n_151), .A1 (n_79), .B0 (n_74), .Y (n_98));
  NAND2XL g2557(.A (n_96), .B (n_95), .Y (n_97));
  OAI21XL g2569(.A0 (n_72), .A1 (n_76), .B0 (n_73), .Y (n_94));
  NOR2BXL g2561(.AN (n_116), .B (n_119), .Y (n_93));
  OAI2BB1XL g2562(.A0N (n_91), .A1N (n_61), .B0 (n_75), .Y (n_92));
  NOR2BXL g2581(.AN (n_90), .B (n_89), .Y (n_102));
  MXI2XL g2570(.A (n_83), .B (n_58), .S0 (n_151), .Y (n_88));
  OAI21XL g2564(.A0 (n_80), .A1 (n_83), .B0 (n_78), .Y (n_84));
  MXI2XL g2583(.A (n_67), .B (n_68), .S0 (n_77), .Y (Di[3]));
  OAI21XL g2565(.A0 (n_80), .A1 (n_79), .B0 (n_78), .Y (n_81));
  AO21X1 g2586(.A0 (n_64), .A1 (n_77), .B0 (n_65), .Y (Di[5]));
  OAI21XL g2566(.A0 (n_60), .A1 (n_76), .B0 (n_75), .Y (n_116));
  NAND2XL g2572(.A (n_79), .B (n_151), .Y (n_74));
  NAND2XL g2573(.A (n_76), .B (n_72), .Y (n_73));
  NAND2XL g2558(.A (n_71), .B (n_70), .Y (n_95));
  MXI2XL g2568(.A (n_34), .B (c[2]), .S0 (n_57), .Y (B[2]));
  OR2X1 g2559(.A (n_71), .B (n_70), .Y (n_96));
  NOR2XL g2589(.A (n_63), .B (n_62), .Y (n_89));
  MXI2XL g2584(.A (n_68), .B (n_67), .S0 (n_66), .Y (Bi[3]));
  OAI21XL g2582(.A0 (n_66), .A1 (n_65), .B0 (n_64), .Y (Bi[5]));
  NAND2XL g2590(.A (n_63), .B (n_62), .Y (n_90));
  INVXL g2579(.A (n_60), .Y (n_61));
  MXI2XL g2591(.A (a[3]), .B (n_71), .S0 (n_48), .Y (n_72));
  OAI211XL g2605(.A0 (n_58), .A1 (c[1]), .B0 (n_3), .C0 (n_33), .Y
       (n_59));
  OA21X1 g2576(.A0 (c[2]), .A1 (n_56), .B0 (n_55), .Y (n_70));
  NAND2BXL g2580(.AN (n_56), .B (n_55), .Y (n_57));
  MXI2XL g2610(.A (n_49), .B (n_53), .S0 (n_40), .Y (Di[1]));
  MXI2XL g2600(.A (n_44), .B (n_45), .S0 (n_47), .Y (Di[2]));
  NOR2XL g2594(.A (a[2]), .B (n_51), .Y (n_80));
  NAND2XL g2593(.A (a[2]), .B (n_51), .Y (n_78));
  MXI2XL g2611(.A (n_49), .B (n_53), .S0 (n_153), .Y (Bi[1]));
  NOR2BXL g2596(.AN (n_48), .B (a[3]), .Y (n_60));
  OR2X1 g2595(.A (n_71), .B (n_48), .Y (n_75));
  MXI2XL g2612(.A (n_42), .B (n_43), .S0 (n_53), .Y (n_62));
  AOI21XL g2597(.A0 (n_36), .A1 (n_47), .B0 (n_37), .Y (n_77));
  MXI2XL g2599(.A (n_45), .B (n_44), .S0 (n_38), .Y (Bi[2]));
  MXI2XL g2603(.A (n_43), .B (n_42), .S0 (n_25), .Y (B[1]));
  OAI222XL g2585(.A0 (n_29), .A1 (n_16), .B0 (n_30), .B1 (n_40), .C0
       (n_8), .C1 (b[0]), .Y (n_41));
  MXI2XL g2608(.A (n_43), .B (n_42), .S0 (n_22), .Y (n_39));
  OAI21XL g2598(.A0 (n_38), .A1 (n_37), .B0 (n_36), .Y (n_66));
  NAND2XL g2587(.A (a[2]), .B (n_35), .Y (n_55));
  NOR2XL g2588(.A (a[2]), .B (n_35), .Y (n_56));
  MXI2XL g2613(.A (n_44), .B (n_45), .S0 (n_34), .Y (n_51));
  AOI22XL g2606(.A0 (n_17), .A1 (c[1]), .B0 (n_12), .B1 (d[1]), .Y
       (n_33));
  MXI2XL g2602(.A (n_31), .B (Bi[0]), .S0 (B[0]), .Y (A[0]));
  MXI2XL g2609(.A (n_68), .B (n_67), .S0 (c[3]), .Y (n_48));
  OAI2BB1XL g2623(.A0N (c[1]), .A1N (a[1]), .B0 (n_23), .Y (n_32));
  OAI2BB1XL g2621(.A0N (n_24), .A1N (n_40), .B0 (n_28), .Y (n_47));
  OAI22XL g2604(.A0 (n_31), .A1 (n_4), .B0 (n_30), .B1 (n_29), .Y
       (n_63));
  INVXL g2625(.A (n_49), .Y (n_53));
  AOI21XL g2622(.A0 (n_28), .A1 (n_153), .B0 (n_10), .Y (n_38));
  INVXL g2624(.A (n_43), .Y (n_42));
  INVXL g2616(.A (n_119), .Y (n_26));
  OAI21XL g2601(.A0 (n_25), .A1 (n_154), .B0 (n_11), .Y (n_35));
  NAND2XL g2629(.A (n_24), .B (n_28), .Y (n_49));
  OAI21XL g2626(.A0 (a[1]), .A1 (c[1]), .B0 (n_22), .Y (n_23));
  OAI21XL g2620(.A0 (n_18), .A1 (n_20), .B0 (n_19), .Y (n_21));
  INVXL g2615(.A (n_31), .Y (Bi[0]));
  OAI21XL g2618(.A0 (n_14), .A1 (n_34), .B0 (n_15), .Y (n_91));
  INVXL g2630(.A (n_67), .Y (n_68));
  AOI21XL g2619(.A0 (c[3]), .A1 (n_19), .B0 (n_18), .Y (n_119));
  OAI21XL g2632(.A0 (n_9), .A1 (d[1]), .B0 (n_28), .Y (n_17));
  AOI211XL g2607(.A0 (c[0]), .A1 (d[0]), .B0 (n_6), .C0 (n_7), .Y
       (n_16));
  AOI21XL g2617(.A0 (c[2]), .A1 (n_15), .B0 (n_14), .Y (n_76));
  AO21X1 g2633(.A0 (a[0]), .A1 (n_30), .B0 (n_25), .Y (B[0]));
  INVXL g2631(.A (n_45), .Y (n_44));
  NOR2XL g2628(.A (n_154), .B (n_12), .Y (n_43));
  OAI21XL g2627(.A0 (b[0]), .A1 (d[0]), .B0 (n_103), .Y (n_31));
  NOR2BXL g2634(.AN (n_64), .B (n_65), .Y (n_67));
  INVXL g2649(.A (n_12), .Y (n_11));
  INVXL g2636(.A (n_10), .Y (n_24));
  NOR2BXL g2635(.AN (n_36), .B (n_37), .Y (n_45));
  NOR2XL g2644(.A (b[1]), .B (n_5), .Y (n_10));
  INVXL g2637(.A (n_58), .Y (n_83));
  NOR2XL g2655(.A (c[1]), .B (n_9), .Y (n_12));
  INVXL g2614(.A (n_7), .Y (n_8));
  NOR2XL g2658(.A (d[0]), .B (n_30), .Y (n_22));
  NAND2XL g2659(.A (d[0]), .B (n_6), .Y (n_40));
  NOR2XL g2660(.A (a[0]), .B (n_30), .Y (n_25));
  NAND2XL g2647(.A (b[1]), .B (n_5), .Y (n_28));
  NOR2XL g2638(.A (c[0]), .B (a[0]), .Y (n_4));
  NAND2XL g2639(.A (b[1]), .B (a[1]), .Y (n_3));
  NAND2XL g2642(.A (d[3]), .B (b[3]), .Y (n_19));
  NAND2BXL g2645(.AN (b[2]), .B (d[2]), .Y (n_36));
  NAND2XL g2643(.A (d[1]), .B (c[1]), .Y (n_79));
  NOR2BXL g2653(.AN (b[2]), .B (d[2]), .Y (n_37));
  NAND2XL g2646(.A (d[0]), .B (b[0]), .Y (n_103));
  NOR2XL g2640(.A (d[2]), .B (b[2]), .Y (n_14));
  NAND2XL g2652(.A (d[2]), .B (b[2]), .Y (n_15));
  NOR2XL g2650(.A (d[0]), .B (c[0]), .Y (n_7));
  NOR2XL g2641(.A (d[3]), .B (b[3]), .Y (n_18));
  NAND2BXL g2654(.AN (d[3]), .B (b[3]), .Y (n_64));
  NAND2XL g2648(.A (d[1]), .B (b[1]), .Y (n_58));
  NOR2BXL g2656(.AN (d[3]), .B (b[3]), .Y (n_65));
  INVXL g2664(.A (d[1]), .Y (n_5));
  INVXL g2661(.A (a[0]), .Y (n_29));
  INVXL g2671(.A (c[0]), .Y (n_30));
  INVXL g2665(.A (a[1]), .Y (n_9));
  INVXL g2663(.A (b[0]), .Y (n_6));
  INVXL g2667(.A (c[3]), .Y (n_20));
  INVXL g2670(.A (c[2]), .Y (n_34));
  INVXL g2662(.A (a[3]), .Y (n_71));
  CLKXOR2X1 g2(.A (n_72), .B (n_91), .Y (n_150));
  CLKXOR2X1 g2672(.A (a[2]), .B (n_51), .Y (n_151));
  NAND2BX1 g2674(.AN (d[0]), .B (b[0]), .Y (n_153));
  NOR2BX1 g2675(.AN (c[1]), .B (a[1]), .Y (n_154));
  XNOR2XL g2676(.A (n_103), .B (n_102), .Y (A[1]));
endmodule

