/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Tue Sep 10 01:20:44 2019
#  Design:            encoder_83
#  Command:           saveNetlist encoder_83_inno_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 19:25:30 IST (Sep  8 2019 13:55:30 UTC)
// Verification Directory fv/encoder_83 
module encoder_83 (
	d, 
	en, 
	y0, 
	y1, 
	y2, 
	v);
   input [7:0] d;
   input en;
   output y0;
   output y1;
   output y2;
   output v;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_10;
   wire n_11;

   OAI31XL g279 (.A0(n_8),
	.A1(d[6]),
	.A2(n_11),
	.B0(n_1),
	.Y(y0));
   NAND2BXL g280 (.AN(y2),
	.B(n_10),
	.Y(v));
   AOI2BB1XL g283 (.A0N(d[4]),
	.A1N(n_5),
	.B0(d[5]),
	.Y(n_11));
   OAI31XL g282 (.A0(d[1]),
	.A1(d[0]),
	.A2(n_4),
	.B0(en),
	.Y(n_10));
   OAI31XL g281 (.A0(n_3),
	.A1(n_8),
	.A2(n_7),
	.B0(n_6),
	.Y(y1));
   OAI2BB1XL g284 (.A0N(en),
	.A1N(n_7),
	.B0(n_6),
	.Y(y2));
   AOI21XL g286 (.A0(en),
	.A1(d[6]),
	.B0(n_2),
	.Y(n_6));
   AOI21XL g285 (.A0(d[1]),
	.A1(n_0),
	.B0(d[3]),
	.Y(n_5));
   INVXL g289 (.A(n_3),
	.Y(n_4));
   INVXL g287 (.A(n_1),
	.Y(n_2));
   NAND2XL g288 (.A(en),
	.B(d[7]),
	.Y(n_1));
   NOR2XL g290 (.A(d[2]),
	.B(d[3]),
	.Y(n_3));
   OR2X1 g291 (.A(d[4]),
	.B(d[5]),
	.Y(n_7));
   INVXL g293 (.A(en),
	.Y(n_8));
   INVXL g292 (.A(d[2]),
	.Y(n_0));
endmodule

