
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 20 2019 18:42:04 IST (Oct 20 2019 13:12:04 UTC)

// Verification Directory fv/dff 

module dff(d, clk, q, q_c);
  input d, clk;
  output q, q_c;
  wire d, clk;
  wire q, q_c;
  INVXL g3(.A (q), .Y (q_c));
  DFFQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

