
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 19:33:32 IST (Sep  4 2019 14:03:32 UTC)

// Verification Directory fv/andgate 

module andgate(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2XL g8(.A (b), .B (a), .Y (y));
endmodule

