/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client04)
#  Generated on:      Tue Oct 22 11:33:56 2019
#  Design:            serial_add
#  Command:           saveNetlist serial_add_inno_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 22 2019 11:17:00 IST (Oct 22 2019 05:47:00 UTC)
// Verification Directory fv/serial_add 
module serial_add (
	clk, 
	rst, 
	a, 
	b, 
	c_in, 
	S, 
	c_out);
   input clk;
   input rst;
   input [3:0] a;
   input [3:0] b;
   input c_in;
   output [3:0] S;
   output c_out;

   // Internal wires
   wire [3:0] z;
   wire [3:0] x;
   wire [3:0] y;
   wire [1:0] temp;
   wire [2:0] i;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_28;
   wire n_45;

   SDFFQXL \S_reg[0]  (.CK(clk),
	.D(z[0]),
	.Q(S[0]),
	.SE(n_28),
	.SI(S[0]));
   SDFFQXL \S_reg[1]  (.CK(clk),
	.D(z[1]),
	.Q(S[1]),
	.SE(n_28),
	.SI(S[1]));
   DFFRHQX1 \z_reg[0]  (.CK(clk),
	.D(z[1]),
	.Q(z[0]),
	.RN(rst));
   SDFFQXL \S_reg[2]  (.CK(clk),
	.D(z[2]),
	.Q(S[2]),
	.SE(n_28),
	.SI(S[2]));
   DFFRHQX1 \z_reg[1]  (.CK(clk),
	.D(z[2]),
	.Q(z[1]),
	.RN(rst));
   SDFFQXL \S_reg[3]  (.CK(clk),
	.D(z[3]),
	.Q(S[3]),
	.SE(n_28),
	.SI(S[3]));
   DFFSRHQX1 \x_reg[0]  (.CK(clk),
	.D(x[1]),
	.Q(x[0]),
	.RN(n_6),
	.SN(n_21));
   DFFRHQX1 \z_reg[2]  (.CK(clk),
	.D(z[3]),
	.Q(z[2]),
	.RN(rst));
   DFFSRHQX1 \y_reg[0]  (.CK(clk),
	.D(y[1]),
	.Q(y[0]),
	.RN(n_2),
	.SN(n_14));
   SDFFQXL c_out_reg (.CK(clk),
	.D(c_out),
	.Q(c_out),
	.SE(n_45),
	.SI(temp[1]));
   DFFRHQX1 \z_reg[3]  (.CK(clk),
	.D(temp[0]),
	.Q(z[3]),
	.RN(rst));
   DFFSRHQX1 \x_reg[1]  (.CK(clk),
	.D(x[2]),
	.Q(x[1]),
	.RN(n_9),
	.SN(n_12));
   DFFSRHQX1 \y_reg[1]  (.CK(clk),
	.D(y[2]),
	.Q(y[1]),
	.RN(n_5),
	.SN(n_18));
   SDFFRHQX1 \temp_reg[0]  (.CK(clk),
	.D(n_25),
	.Q(temp[0]),
	.RN(rst),
	.SE(temp[1]),
	.SI(n_24));
   DFFSRHQX1 \temp_reg[1]  (.CK(clk),
	.D(n_26),
	.Q(temp[1]),
	.RN(n_4),
	.SN(n_11));
   DFFSRHQX1 \x_reg[2]  (.CK(clk),
	.D(x[3]),
	.Q(x[2]),
	.RN(n_7),
	.SN(n_15));
   DFFSRHQX1 \y_reg[2]  (.CK(clk),
	.D(y[3]),
	.Q(y[2]),
	.RN(n_0),
	.SN(n_17));
   DFFSRHQX1 \x_reg[3]  (.CK(clk),
	.D(x[0]),
	.Q(x[3]),
	.RN(n_3),
	.SN(n_13));
   NAND3X2 g610 (.A(i[0]),
	.B(n_22),
	.C(rst),
	.Y(n_28));
   DFFSRHQX1 \y_reg[3]  (.CK(clk),
	.D(y[0]),
	.Q(y[3]),
	.RN(n_8),
	.SN(n_19));
   AO22X1 g598 (.A0(temp[1]),
	.A1(n_25),
	.B0(y[0]),
	.B1(x[0]),
	.Y(n_26));
   SDFFRHQX1 \i_reg[2]  (.CK(clk),
	.D(n_16),
	.Q(i[2]),
	.RN(rst),
	.SE(n_1),
	.SI(i[2]));
   SDFFRHQX1 \i_reg[1]  (.CK(clk),
	.D(i[0]),
	.Q(i[1]),
	.RN(rst),
	.SE(i[1]),
	.SI(n_10));
   INVXL g606 (.A(n_25),
	.Y(n_24));
   NAND2XL g628 (.A(a[0]),
	.B(n_20),
	.Y(n_21));
   NAND2XL g629 (.A(b[3]),
	.B(n_20),
	.Y(n_19));
   NAND2XL g630 (.A(b[1]),
	.B(n_20),
	.Y(n_18));
   NAND2XL g631 (.A(b[2]),
	.B(n_20),
	.Y(n_17));
   NOR2XL g635 (.A(i[1]),
	.B(n_16),
	.Y(n_22));
   CLKXOR2X1 g613 (.A(x[0]),
	.B(y[0]),
	.Y(n_25));
   NAND2XL g616 (.A(a[2]),
	.B(n_20),
	.Y(n_15));
   NAND2XL g620 (.A(b[0]),
	.B(n_20),
	.Y(n_14));
   NAND2XL g626 (.A(a[3]),
	.B(n_20),
	.Y(n_13));
   NAND2XL g621 (.A(a[1]),
	.B(n_20),
	.Y(n_12));
   NAND2XL g622 (.A(c_in),
	.B(n_20),
	.Y(n_11));
   OR2X1 g633 (.A(a[1]),
	.B(rst),
	.Y(n_9));
   OR2X1 g632 (.A(b[3]),
	.B(rst),
	.Y(n_8));
   OR2X1 g627 (.A(a[2]),
	.B(rst),
	.Y(n_7));
   OR2X1 g614 (.A(a[0]),
	.B(rst),
	.Y(n_6));
   OR2X1 g615 (.A(b[1]),
	.B(rst),
	.Y(n_5));
   OR2X1 g619 (.A(c_in),
	.B(rst),
	.Y(n_4));
   OR2X1 g618 (.A(a[3]),
	.B(rst),
	.Y(n_3));
   OR2X1 g617 (.A(b[0]),
	.B(rst),
	.Y(n_2));
   NAND2XL g634 (.A(i[1]),
	.B(i[0]),
	.Y(n_1));
   OR2X1 g625 (.A(b[2]),
	.B(rst),
	.Y(n_0));
   CLKINVX3 g637 (.A(rst),
	.Y(n_20));
   CLKINVX1 g636 (.A(i[2]),
	.Y(n_16));
   DFFRX1 \i_reg[0]  (.CK(clk),
	.D(n_10),
	.Q(i[0]),
	.QN(n_10),
	.RN(rst));
   NOR3BX1 g2 (.AN(n_22),
	.B(i[0]),
	.C(n_20),
	.Y(n_45));
endmodule

