
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 17:35:41 IST (Sep  4 2019 12:05:41 UTC)

// Verification Directory fv/orgate 

module orgate(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  OR2X1 g2(.A (b), .B (a), .Y (y));
endmodule

