/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Tue Sep 10 00:48:06 2019
#  Design:            demux_14
#  Command:           saveNetlist demux_14_inno_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:58:29 IST (Sep  8 2019 13:28:29 UTC)
// Verification Directory fv/demux_14 
module demux_12 (
	s, 
	d, 
	y0, 
	y1);
   input s;
   input d;
   output y0;
   output y1;

   NOR2BXL g17 (.AN(d),
	.B(s),
	.Y(y0));
   AND2X1 g18 (.A(d),
	.B(s),
	.Y(y1));
endmodule

module demux_12_1 (
	s, 
	d, 
	y0, 
	y1);
   input s;
   input d;
   output y0;
   output y1;

   NOR2BXL g17 (.AN(d),
	.B(s),
	.Y(y0));
   AND2XL g18 (.A(s),
	.B(d),
	.Y(y1));
endmodule

module demux_12_2 (
	s, 
	d, 
	y0, 
	y1);
   input s;
   input d;
   output y0;
   output y1;

   NOR2BXL g17 (.AN(d),
	.B(s),
	.Y(y0));
   AND2XL g18 (.A(s),
	.B(d),
	.Y(y1));
endmodule

module demux_14 (
	d, 
	s0, 
	s1, 
	y0, 
	y1, 
	y2, 
	y3);
   input d;
   input s0;
   input s1;
   output y0;
   output y1;
   output y2;
   output y3;

   // Internal wires
   wire z0;
   wire z1;

   demux_12 demux1 (.s(s1),
	.d(d),
	.y0(z0),
	.y1(z1));
   demux_12_1 demux2 (.s(s0),
	.d(z0),
	.y0(y0),
	.y1(y1));
   demux_12_2 demux3 (.s(s0),
	.d(z1),
	.y0(y2),
	.y1(y3));
endmodule

