
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:50:11 IST (Sep  8 2019 13:20:11 UTC)

// Verification Directory fv/mux_41 

module mux_21(a, b, c, y);
  input a, b, c;
  output y;
  wire a, b, c;
  wire y;
  MX2X1 g24(.A (a), .B (b), .S0 (c), .Y (y));
endmodule

module mux_21_1(a, b, c, y);
  input a, b, c;
  output y;
  wire a, b, c;
  wire y;
  MX2X1 g24(.A (a), .B (b), .S0 (c), .Y (y));
endmodule

module mux_21_2(a, b, c, y);
  input a, b, c;
  output y;
  wire a, b, c;
  wire y;
  MX2X1 g24(.A (a), .B (b), .S0 (c), .Y (y));
endmodule

module mux_41(i0, i1, i2, i3, s0, s1, y);
  input i0, i1, i2, i3, s0, s1;
  output y;
  wire i0, i1, i2, i3, s0, s1;
  wire y;
  wire mux1, mux2;
  mux_21 mux_1(i0, i2, s0, mux1);
  mux_21_1 mux_2(i1, i3, s0, mux2);
  mux_21_2 mux_3(mux1, mux2, s1, y);
endmodule

