
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 19:28:50 IST (Sep  4 2019 13:58:50 UTC)

// Verification Directory fv/xnorgate 

module xnorgate(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  wire n_0;
  OAI21XL g10(.A0 (a), .A1 (b), .B0 (n_0), .Y (y));
  NAND2XL g11(.A (b), .B (a), .Y (n_0));
endmodule

