
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 19:11:12 IST (Sep  8 2019 13:41:12 UTC)

// Verification Directory fv/dec_12 

module dec_12(a, in, y0, y1);
  input a, in;
  output y0, y1;
  wire a, in;
  wire y0, y1;
  NOR2BXL g17(.AN (in), .B (a), .Y (y0));
  AND2XL g18(.A (in), .B (a), .Y (y1));
endmodule

