
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 19:27:05 IST (Sep  4 2019 13:57:05 UTC)

// Verification Directory fv/xorgate 

module xorgate(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  CLKXOR2X1 g10(.A (b), .B (a), .Y (y));
endmodule

