
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  1 2019 01:04:40 IST (Aug 31 2019 19:34:40 UTC)

// Verification Directory fv/comb_cktb 

module comb_cktb(a, b, c, d, e, f, y);
  input a, b, c, d, e, f;
  output y;
  wire a, b, c, d, e, f;
  wire y;
  wire n_0;
  NOR2BXL g45(.AN (f), .B (n_0), .Y (y));
  AOI32XL g46(.A0 (c), .A1 (b), .A2 (a), .B0 (d), .B1 (e), .Y (n_0));
endmodule

