
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 19:17:32 IST (Sep  8 2019 13:47:32 UTC)

// Verification Directory fv/dec_24 

module dec_12(a, in, y0, y1);
  input a, in;
  output y0, y1;
  wire a, in;
  wire y0, y1;
  NOR2BXL g17(.AN (in), .B (a), .Y (y0));
  AND2X1 g18(.A (in), .B (a), .Y (y1));
endmodule

module dec_12_1(a, in, y0, y1);
  input a, in;
  output y0, y1;
  wire a, in;
  wire y0, y1;
  NOR2BXL g17(.AN (in), .B (a), .Y (y0));
  AND2XL g18(.A (a), .B (in), .Y (y1));
endmodule

module dec_12_2(a, in, y0, y1);
  input a, in;
  output y0, y1;
  wire a, in;
  wire y0, y1;
  NOR2BXL g17(.AN (in), .B (a), .Y (y0));
  AND2XL g18(.A (a), .B (in), .Y (y1));
endmodule

module dec_24(a0, a1, in, d0, d1, d2, d3);
  input a0, a1, in;
  output d0, d1, d2, d3;
  wire a0, a1, in;
  wire d0, d1, d2, d3;
  wire y0, y1;
  dec_12 dec_1(a1, in, y0, y1);
  dec_12_1 dec_2(a0, y0, d0, d1);
  dec_12_2 dec_3(a0, y1, d2, d3);
endmodule

