
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  1 2019 01:02:02 IST (Aug 31 2019 19:32:02 UTC)

// Verification Directory fv/comb_ckta 

module comb_ckta(a, b, c, d, y);
  input a, b, c, d;
  output y;
  wire a, b, c, d;
  wire y;
  AO22X1 g20(.A0 (d), .A1 (c), .B0 (b), .B1 (a), .Y (y));
endmodule

