
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:45:23 IST (Sep  8 2019 13:15:23 UTC)

// Verification Directory fv/mux_21 

module mux_21(a, b, c, y);
  input a, b, c;
  output y;
  wire a, b, c;
  wire y;
  MX2X1 g24(.A (a), .B (b), .S0 (c), .Y (y));
endmodule

