
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  1 2019 21:10:06 IST (Sep  1 2019 15:40:06 UTC)

// Verification Directory fv/comb_cktc 

module comb_cktc(a, b, c, d, e, y);
  input a, b, c, d, e;
  output y;
  wire a, b, c, d, e;
  wire y;
  wire n_0, n_1;
  OAI22XL g33(.A0 (n_1), .A1 (e), .B0 (n_0), .B1 (a), .Y (y));
  AND2X1 g34(.A (d), .B (c), .Y (n_1));
  INVXL g35(.A (b), .Y (n_0));
endmodule

