/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Mon Sep  9 21:48:08 2019
#  Design:            mux_41
#  Command:           saveNetlist mux_41_inno_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:50:11 IST (Sep  8 2019 13:20:11 UTC)
// Verification Directory fv/mux_41 
module mux_21 (
	a, 
	b, 
	c, 
	y);
   input a;
   input b;
   input c;
   output y;

   MX2X1 g24 (.A(a),
	.B(b),
	.S0(c),
	.Y(y));
endmodule

module mux_21_1 (
	a, 
	b, 
	c, 
	y);
   input a;
   input b;
   input c;
   output y;

   MX2X1 g24 (.A(a),
	.B(b),
	.S0(c),
	.Y(y));
endmodule

module mux_21_2 (
	a, 
	b, 
	c, 
	y);
   input a;
   input b;
   input c;
   output y;

   MX2X1 g24 (.A(a),
	.B(b),
	.S0(c),
	.Y(y));
endmodule

module mux_41 (
	i0, 
	i1, 
	i2, 
	i3, 
	s0, 
	s1, 
	y);
   input i0;
   input i1;
   input i2;
   input i3;
   input s0;
   input s1;
   output y;

   // Internal wires
   wire mux1;
   wire mux2;

   mux_21 mux_1 (.a(i0),
	.b(i2),
	.c(s0),
	.y(mux1));
   mux_21_1 mux_2 (.a(i1),
	.b(i3),
	.c(s0),
	.y(mux2));
   mux_21_2 mux_3 (.a(mux1),
	.b(mux2),
	.c(s1),
	.y(y));
endmodule

