
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 26 2019 18:58:41 IST (Sep 26 2019 13:28:41 UTC)

// Verification Directory fv/rcarry_4bit 

module fa_1bit(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (cin), .B (b), .CI (a), .CO (cout), .S (s));
endmodule

module fa_1bit_1(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (b), .B (a), .CI (cin), .CO (cout), .S (s));
endmodule

module fa_1bit_2(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (b), .B (a), .CI (cin), .CO (cout), .S (s));
endmodule

module fa_1bit_3(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (b), .B (a), .CI (cin), .CO (cout), .S (s));
endmodule

module rcarry_4bit(a, b, cin, s, cout);
  input [3:0] a, b;
  input cin;
  output [3:0] s;
  output cout;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] s;
  wire cout;
  wire \carry[1] , \carry[2] , \carry[3] ;
  fa_1bit FA1(a[0], b[0], cin, s[0], \carry[1] );
  fa_1bit_1 FA2(a[1], b[1], \carry[1] , s[1], \carry[2] );
  fa_1bit_2 FA3(a[2], b[2], \carry[2] , s[2], \carry[3] );
  fa_1bit_3 FA4(a[3], b[3], \carry[3] , s[3], cout);
endmodule

