
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 18:44:01 IST (Sep  4 2019 13:14:01 UTC)

// Verification Directory fv/norgate 

module norgate(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  NOR2XL g10(.A (b), .B (a), .Y (y));
endmodule

