
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct  9 2019 22:42:24 IST (Oct  9 2019 17:12:24 UTC)

// Verification Directory fv/wallace 

module fa(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (cin), .B (a), .CI (b), .CO (cout), .S (s));
endmodule

module fa_1(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (cin), .B (a), .CI (b), .CO (cout), .S (s));
endmodule

module fa_2(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (cin), .B (a), .CI (b), .CO (cout), .S (s));
endmodule

module fa_3(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (cin), .B (b), .CI (a), .CO (cout), .S (s));
endmodule

module fa_4(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (cin), .B (a), .CI (b), .CO (cout), .S (s));
endmodule

module fa_5(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (b), .B (a), .CI (cin), .CO (cout), .S (s));
endmodule

module fa_6(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  ADDFX1 g2(.A (cin), .B (a), .CI (b), .CO (cout), .S (s));
endmodule

module ha(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  ADDHXL g17(.A (a), .B (b), .CO (cout), .S (s));
endmodule

module ha_1(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  ADDHXL g17(.A (a), .B (b), .CO (cout), .S (s));
endmodule

module ha_3(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  ADDHXL g17(.A (b), .B (a), .CO (cout), .S (s));
endmodule

module ha_4(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  ADDHXL g17(.A (b), .B (a), .CO (cout), .S (s));
endmodule

module ha_5(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  ADDHXL g17(.A (b), .B (a), .CO (cout), .S (s));
endmodule

module ha_6(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  ADDHXL g17(.A (b), .B (a), .CO (cout), .S (s));
endmodule

module ha_2(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  ADDHXL g17(.A (a), .B (b), .CO (cout), .S (s));
endmodule

module ha_7(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  CLKXOR2X1 g11(.A (b), .B (a), .Y (s));
endmodule

module wallace(A, B, prod);
  input [3:0] A, B;
  output [7:0] prod;
  wire [3:0] A, B;
  wire [7:0] prod;
  wire C3, C4, C5, C6, C7, c1, c2, c3;
  wire c4, c5, c_2, c_3, c_4, c_5, c_6, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, p3, p4;
  wire p5, p6, r2, r3, r4, r5;
  fa fa1(n_28, n_27, n_26, r2, c2);
  fa_1 fa2(n_25, n_24, n_23, r3, c3);
  fa_2 fa3(n_22, n_21, n_20, r4, c4);
  fa_3 fa5(r3, c2, n_17, p3, c_3);
  fa_4 fa6(c3, C3, r4, p4, c_4);
  fa_5 fa7(c4, r5, c_4, p5, c_5);
  fa_6 fa8(c5, c_5, n_16, p6, c_6);
  ha ha1(n_30, n_29, prod[1], c1);
  ha_1 ha2(n_19, n_18, r5, c5);
  ha_3 ha3(p3, c_2, prod[3], C3);
  ha_4 ha4(p4, c_3, prod[4], C4);
  ha_5 ha5(p5, C4, prod[5], C5);
  ha_6 ha6(p6, C5, prod[6], C6);
  ha_2 ha7(c1, r2, prod[2], c_2);
  ha_7 ha8(C6, c_6, prod[7], C7);
  AND2X1 g113(.A (B[3]), .B (A[2]), .Y (n_18));
  AND2X1 g114(.A (B[0]), .B (A[1]), .Y (n_30));
  AND2X1 g115(.A (B[0]), .B (A[2]), .Y (n_28));
  AND2X1 g116(.A (B[3]), .B (A[0]), .Y (n_17));
  AND2XL g117(.A (B[0]), .B (A[0]), .Y (prod[0]));
  AND2X1 g118(.A (B[2]), .B (A[1]), .Y (n_23));
  AND2X1 g119(.A (B[1]), .B (A[3]), .Y (n_22));
  AND2X1 g120(.A (B[2]), .B (A[2]), .Y (n_21));
  AND2X1 g121(.A (B[1]), .B (A[0]), .Y (n_29));
  AND2X1 g122(.A (B[1]), .B (A[1]), .Y (n_27));
  AND2X1 g123(.A (B[2]), .B (A[3]), .Y (n_19));
  AND2X1 g124(.A (B[2]), .B (A[0]), .Y (n_26));
  AND2X1 g125(.A (B[3]), .B (A[1]), .Y (n_20));
  AND2X1 g126(.A (B[0]), .B (A[3]), .Y (n_25));
  AND2X1 g127(.A (B[3]), .B (A[3]), .Y (n_16));
  AND2X1 g128(.A (B[1]), .B (A[2]), .Y (n_24));
endmodule

