
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 22 2019 11:22:15 IST (Oct 22 2019 05:52:15 UTC)

// Verification Directory fv/serialmul 

module serialmul(clk, rst, a, b, P);
  input clk, rst;
  input [3:0] a, b;
  output [7:0] P;
  wire clk, rst;
  wire [3:0] a, b;
  wire [7:0] P;
  wire [7:0] z;
  wire [3:0] x;
  wire [2:0] i;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  DFFRHQX1 \z_reg[7] (.RN (rst), .CK (clk), .D (n_31), .Q (z[7]));
  SDFFQXL \P_reg[0] (.CK (clk), .D (P[0]), .SI (z[0]), .SE (n_28), .Q
       (P[0]));
  SDFFRHQX1 \z_reg[6] (.RN (rst), .CK (clk), .D (n_30), .SI (n_22), .SE
       (n_29), .Q (z[6]));
  AO22XL g1427(.A0 (n_30), .A1 (n_29), .B0 (n_19), .B1 (z[7]), .Y
       (n_31));
  SDFFQXL \P_reg[1] (.CK (clk), .D (P[1]), .SI (z[1]), .SE (n_28), .Q
       (P[1]));
  SDFFRHQX1 \z_reg[5] (.RN (rst), .CK (clk), .D (n_26), .SI (n_25), .SE
       (n_27), .Q (z[5]));
  DFFRHQX1 \z_reg[0] (.RN (rst), .CK (clk), .D (z[1]), .Q (z[0]));
  SDFFQXL \P_reg[2] (.CK (clk), .D (P[2]), .SI (z[2]), .SE (n_28), .Q
       (P[2]));
  OAI22X1 g1429(.A0 (n_27), .A1 (n_26), .B0 (n_17), .B1 (n_18), .Y
       (n_29));
  DFFSRHQX1 \x_reg[0] (.RN (n_4), .SN (n_12), .CK (clk), .D (x[1]), .Q
       (x[0]));
  DFFRHQX1 \z_reg[1] (.RN (rst), .CK (clk), .D (z[2]), .Q (z[1]));
  SDFFQXL \P_reg[3] (.CK (clk), .D (P[3]), .SI (z[3]), .SE (n_28), .Q
       (P[3]));
  INVXL g1435(.A (n_26), .Y (n_25));
  DFFSRHQX1 \x_reg[1] (.RN (n_2), .SN (n_8), .CK (clk), .D (x[2]), .Q
       (x[1]));
  SDFFQXL \P_reg[6] (.CK (clk), .D (P[6]), .SI (z[6]), .SE (n_28), .Q
       (P[6]));
  SDFFQXL \P_reg[5] (.CK (clk), .D (P[5]), .SI (z[5]), .SE (n_28), .Q
       (P[5]));
  SDFFQXL \P_reg[7] (.CK (clk), .D (P[7]), .SI (z[7]), .SE (n_28), .Q
       (P[7]));
  SDFFQXL \P_reg[4] (.CK (clk), .D (P[4]), .SI (z[4]), .SE (n_28), .Q
       (P[4]));
  SDFFRHQX1 \z_reg[4] (.RN (rst), .CK (clk), .D (n_24), .SI (n_21), .SE
       (n_23), .Q (z[4]));
  AOI22X1 g1437(.A0 (n_24), .A1 (n_23), .B0 (n_20), .B1 (z[5]), .Y
       (n_26));
  DFFRHQX1 \z_reg[2] (.RN (rst), .CK (clk), .D (z[3]), .Q (z[2]));
  DFFSRHQX1 \x_reg[2] (.RN (n_1), .SN (n_13), .CK (clk), .D (x[3]), .Q
       (x[2]));
  SDFFRHQX1 \z_reg[3] (.RN (rst), .CK (clk), .D (n_16), .SI (n_10), .SE
       (z[4]), .Q (z[3]));
  INVXL g1448(.A (n_30), .Y (n_22));
  CLKINVX1 g1447(.A (n_21), .Y (n_24));
  MXI2XL g1453(.A (n_6), .B (n_20), .S0 (z[5]), .Y (n_23));
  AND2X4 g1452(.A (n_15), .B (rst), .Y (n_28));
  DFFSRHQX1 \x_reg[3] (.RN (n_3), .SN (n_7), .CK (clk), .D (x[0]), .Q
       (x[3]));
  SDFFRHQX1 \i_reg[2] (.RN (rst), .CK (clk), .D (n_14), .SI (i[2]), .SE
       (n_0), .Q (i[2]));
  MXI2XL g1455(.A (n_9), .B (n_19), .S0 (z[7]), .Y (n_30));
  MXI2XL g1454(.A (n_18), .B (z[6]), .S0 (n_17), .Y (n_27));
  NAND2XL g1458(.A (n_16), .B (z[4]), .Y (n_21));
  SDFFRHQX1 \i_reg[1] (.RN (rst), .CK (clk), .D (i[0]), .SI (n_5), .SE
       (i[1]), .Q (i[1]));
  NOR3X1 g1457(.A (i[1]), .B (i[0]), .C (n_14), .Y (n_15));
  NAND2XL g1462(.A (a[2]), .B (n_11), .Y (n_13));
  NAND2XL g1461(.A (a[0]), .B (n_11), .Y (n_12));
  CLKINVX1 g1468(.A (n_10), .Y (n_16));
  CLKINVX1 g1460(.A (n_9), .Y (n_19));
  NAND2XL g1473(.A (a[1]), .B (n_11), .Y (n_8));
  NAND2XL g1469(.A (a[3]), .B (n_11), .Y (n_7));
  CLKINVX1 g1459(.A (n_6), .Y (n_20));
  OR2X1 g1463(.A (a[0]), .B (rst), .Y (n_4));
  NAND2XL g1464(.A (b[2]), .B (x[0]), .Y (n_17));
  NAND2XL g1465(.A (b[1]), .B (x[0]), .Y (n_6));
  NAND2XL g1466(.A (b[3]), .B (x[0]), .Y (n_9));
  OR2X1 g1472(.A (a[3]), .B (rst), .Y (n_3));
  OR2X1 g1471(.A (a[1]), .B (rst), .Y (n_2));
  OR2X1 g1470(.A (a[2]), .B (rst), .Y (n_1));
  NAND2XL g1474(.A (i[1]), .B (i[0]), .Y (n_0));
  NAND2XL g1475(.A (b[0]), .B (x[0]), .Y (n_10));
  CLKINVX1 g1476(.A (z[6]), .Y (n_18));
  CLKINVX1 g1477(.A (i[2]), .Y (n_14));
  INVXL g1479(.A (rst), .Y (n_11));
  DFFRX1 \i_reg[0] (.RN (rst), .CK (clk), .D (n_5), .Q (i[0]), .QN
       (n_5));
endmodule

