
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 17:36:46 IST (Sep  4 2019 12:06:46 UTC)

// Verification Directory fv/notgate 

module notgate(a, y);
  input a;
  output y;
  wire a;
  wire y;
  INVXL g2(.A (a), .Y (y));
endmodule

