
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 18:44:56 IST (Sep  4 2019 13:14:56 UTC)

// Verification Directory fv/nandgate 

module nandgate(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  NAND2XL g4(.A (b), .B (a), .Y (y));
endmodule

