
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 26 2019 19:17:25 IST (Sep 26 2019 13:47:25 UTC)

// Verification Directory fv/cla_16bit 

module cla_4bit(a, b, cin, cout, s);
  input [3:0] a, b;
  input cin;
  output cout;
  output [3:0] s;
  wire [3:0] a, b;
  wire cin;
  wire cout;
  wire [3:0] s;
  wire n_1, n_3, n_4, n_5, n_6, n_7;
  OAI2BB1XL g244(.A0N (a[3]), .A1N (n_6), .B0 (n_7), .Y (cout));
  OAI21XL g245(.A0 (n_6), .A1 (a[3]), .B0 (b[3]), .Y (n_7));
  OAI2BB1XL g246(.A0N (b[2]), .A1N (n_4), .B0 (n_5), .Y (n_6));
  OAI21XL g247(.A0 (n_4), .A1 (b[2]), .B0 (a[2]), .Y (n_5));
  OAI2BB1XL g248(.A0N (b[1]), .A1N (a[1]), .B0 (n_3), .Y (n_4));
  OAI21XL g249(.A0 (a[1]), .A1 (b[1]), .B0 (n_1), .Y (n_3));
  ADDFX1 g250(.A (b[0]), .B (a[0]), .CI (cin), .CO (n_1), .S (s[0]));
endmodule

module cla_4bit_1(a, b, cin, cout, s);
  input [3:0] a, b;
  input cin;
  output cout;
  output [3:0] s;
  wire [3:0] a, b;
  wire cin;
  wire cout;
  wire [3:0] s;
  wire n_1, n_3, n_4, n_5, n_6, n_7;
  OAI2BB1XL g244(.A0N (a[3]), .A1N (n_6), .B0 (n_7), .Y (cout));
  OAI21XL g245(.A0 (n_6), .A1 (a[3]), .B0 (b[3]), .Y (n_7));
  OAI2BB1XL g246(.A0N (b[2]), .A1N (n_4), .B0 (n_5), .Y (n_6));
  OAI21XL g247(.A0 (n_4), .A1 (b[2]), .B0 (a[2]), .Y (n_5));
  OAI2BB1XL g248(.A0N (b[1]), .A1N (a[1]), .B0 (n_3), .Y (n_4));
  OAI21XL g249(.A0 (a[1]), .A1 (b[1]), .B0 (n_1), .Y (n_3));
  ADDFX1 g250(.A (b[0]), .B (a[0]), .CI (cin), .CO (n_1), .S (s[0]));
endmodule

module cla_4bit_2(a, b, cin, cout, s);
  input [3:0] a, b;
  input cin;
  output cout;
  output [3:0] s;
  wire [3:0] a, b;
  wire cin;
  wire cout;
  wire [3:0] s;
  wire n_1, n_3, n_4, n_5, n_6, n_7;
  OAI2BB1XL g244(.A0N (a[3]), .A1N (n_6), .B0 (n_7), .Y (cout));
  OAI21XL g245(.A0 (n_6), .A1 (a[3]), .B0 (b[3]), .Y (n_7));
  OAI2BB1XL g246(.A0N (b[2]), .A1N (n_4), .B0 (n_5), .Y (n_6));
  OAI21XL g247(.A0 (n_4), .A1 (b[2]), .B0 (a[2]), .Y (n_5));
  OAI2BB1XL g248(.A0N (b[1]), .A1N (a[1]), .B0 (n_3), .Y (n_4));
  OAI21XL g249(.A0 (a[1]), .A1 (b[1]), .B0 (n_1), .Y (n_3));
  ADDFX1 g250(.A (b[0]), .B (a[0]), .CI (cin), .CO (n_1), .S (s[0]));
endmodule

module cla_4bit_3(a, b, cin, cout, s);
  input [3:0] a, b;
  input cin;
  output cout;
  output [3:0] s;
  wire [3:0] a, b;
  wire cin;
  wire cout;
  wire [3:0] s;
  wire n_1, n_3, n_4, n_5, n_6, n_7;
  OAI2BB1XL g244(.A0N (a[3]), .A1N (n_6), .B0 (n_7), .Y (cout));
  OAI21XL g245(.A0 (n_6), .A1 (a[3]), .B0 (b[3]), .Y (n_7));
  OAI2BB1XL g246(.A0N (b[2]), .A1N (n_4), .B0 (n_5), .Y (n_6));
  OAI21XL g247(.A0 (n_4), .A1 (b[2]), .B0 (a[2]), .Y (n_5));
  OAI2BB1XL g248(.A0N (b[1]), .A1N (a[1]), .B0 (n_3), .Y (n_4));
  OAI21XL g249(.A0 (a[1]), .A1 (b[1]), .B0 (n_1), .Y (n_3));
  ADDFX1 g250(.A (b[0]), .B (a[0]), .CI (cin), .CO (n_1), .S (s[0]));
endmodule

module cla_16bit(a, b, cin, s, cout);
  input [15:0] a, b;
  input cin;
  output [15:0] s;
  output cout;
  wire [15:0] a, b;
  wire cin;
  wire [15:0] s;
  wire cout;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, c1, c2,
       c3;
  cla_4bit rc_1(a[3:0], b[3:0], cin, s[0], {UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED, c1});
  cla_4bit_1 rc_2(a[7:4], b[7:4], c1, s[4], {UNCONNECTED4,
       UNCONNECTED3, UNCONNECTED2, c2});
  cla_4bit_2 rc_3(a[11:8], b[11:8], c2, s[8], {UNCONNECTED7,
       UNCONNECTED6, UNCONNECTED5, c3});
  cla_4bit_3 rc_4(a[15:12], b[15:12], c3, s[12], {UNCONNECTED10,
       UNCONNECTED9, UNCONNECTED8, cout});
endmodule

