
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 10 2019 23:09:38 IST (Nov 10 2019 17:39:38 UTC)

// Verification Directory fv/USR 

module dff(q, d, clk, reset);
  input d, clk, reset;
  output q;
  wire d, clk, reset;
  wire q;
  wire UNCONNECTED, n_1;
  DFFNSRXL q_reg(.RN (1'b1), .SN (1'b1), .CKN (clk), .D (n_1), .Q (q),
       .QN (UNCONNECTED));
  NOR2BX1 g6(.AN (d), .B (reset), .Y (n_1));
endmodule

module dff_1(q, d, clk, reset);
  input d, clk, reset;
  output q;
  wire d, clk, reset;
  wire q;
  wire UNCONNECTED0, n_1;
  DFFNSRXL q_reg(.RN (1'b1), .SN (1'b1), .CKN (clk), .D (n_1), .Q (q),
       .QN (UNCONNECTED0));
  NOR2BX1 g6(.AN (d), .B (reset), .Y (n_1));
endmodule

module dff_2(q, d, clk, reset);
  input d, clk, reset;
  output q;
  wire d, clk, reset;
  wire q;
  wire UNCONNECTED1, n_1;
  DFFNSRXL q_reg(.RN (1'b1), .SN (1'b1), .CKN (clk), .D (n_1), .Q (q),
       .QN (UNCONNECTED1));
  NOR2BX1 g6(.AN (d), .B (reset), .Y (n_1));
endmodule

module dff_3(q, d, clk, reset);
  input d, clk, reset;
  output q;
  wire d, clk, reset;
  wire q;
  wire UNCONNECTED2, n_1;
  DFFNSRXL q_reg(.RN (1'b1), .SN (1'b1), .CKN (clk), .D (n_1), .Q (q),
       .QN (UNCONNECTED2));
  NOR2BX1 g6(.AN (d), .B (reset), .Y (n_1));
endmodule

module mux(y, s1, s0, i3, i2, i1, i0);
  input s1, s0, i3, i2, i1, i0;
  output y;
  wire s1, s0, i3, i2, i1, i0;
  wire y;
  MX4XL g143(.A (i0), .B (i1), .C (i2), .D (i3), .S0 (s1), .S1 (s0), .Y
       (y));
endmodule

module mux_1(y, s1, s0, i3, i2, i1, i0);
  input s1, s0, i3, i2, i1, i0;
  output y;
  wire s1, s0, i3, i2, i1, i0;
  wire y;
  MX4XL g143(.A (i0), .B (i1), .C (i2), .D (i3), .S0 (s1), .S1 (s0), .Y
       (y));
endmodule

module mux_2(y, s1, s0, i3, i2, i1, i0);
  input s1, s0, i3, i2, i1, i0;
  output y;
  wire s1, s0, i3, i2, i1, i0;
  wire y;
  MX4XL g143(.A (i0), .B (i1), .C (i2), .D (i3), .S0 (s1), .S1 (s0), .Y
       (y));
endmodule

module mux_3(y, s1, s0, i3, i2, i1, i0);
  input s1, s0, i3, i2, i1, i0;
  output y;
  wire s1, s0, i3, i2, i1, i0;
  wire y;
  MX4XL g143(.A (i0), .B (i1), .C (i2), .D (i3), .S0 (s1), .S1 (s0), .Y
       (y));
endmodule

module USR(I, O, clk, reset, s, SINR, SINL);
  input [3:0] I;
  input clk, reset, SINR, SINL;
  input [1:0] s;
  output [3:0] O;
  wire [3:0] I;
  wire clk, reset, SINR, SINL;
  wire [1:0] s;
  wire [3:0] O;
  wire [3:0] w;
  dff d1(O[0], w[0], clk, reset);
  dff_1 d2(O[1], w[1], clk, reset);
  dff_2 d3(O[2], w[2], clk, reset);
  dff_3 d4(O[3], w[3], clk, reset);
  mux m1(w[0], s[1], s[0], I[0], SINL, O[1], O[0]);
  mux_1 m2(w[1], s[1], s[0], I[1], O[0], O[2], O[1]);
  mux_2 m3(w[2], s[1], s[0], I[2], O[1], O[3], O[2]);
  mux_3 m4(w[3], s[1], s[0], I[3], O[2], SINR, O[3]);
endmodule

