
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:58:29 IST (Sep  8 2019 13:28:29 UTC)

// Verification Directory fv/demux_14 

module demux_12(s, d, y0, y1);
  input s, d;
  output y0, y1;
  wire s, d;
  wire y0, y1;
  NOR2BXL g17(.AN (d), .B (s), .Y (y0));
  AND2X1 g18(.A (d), .B (s), .Y (y1));
endmodule

module demux_12_1(s, d, y0, y1);
  input s, d;
  output y0, y1;
  wire s, d;
  wire y0, y1;
  NOR2BXL g17(.AN (d), .B (s), .Y (y0));
  AND2XL g18(.A (s), .B (d), .Y (y1));
endmodule

module demux_12_2(s, d, y0, y1);
  input s, d;
  output y0, y1;
  wire s, d;
  wire y0, y1;
  NOR2BXL g17(.AN (d), .B (s), .Y (y0));
  AND2XL g18(.A (s), .B (d), .Y (y1));
endmodule

module demux_14(d, s0, s1, y0, y1, y2, y3);
  input d, s0, s1;
  output y0, y1, y2, y3;
  wire d, s0, s1;
  wire y0, y1, y2, y3;
  wire z0, z1;
  demux_12 demux1(s1, d, z0, z1);
  demux_12_1 demux2(s0, z0, y0, y1);
  demux_12_2 demux3(s0, z1, y2, y3);
endmodule

