
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:46:30 IST (Sep  8 2019 13:16:30 UTC)

// Verification Directory fv/demux_12 

module demux_12(s, d, y0, y1);
  input s, d;
  output y0, y1;
  wire s, d;
  wire y0, y1;
  NOR2BXL g17(.AN (d), .B (s), .Y (y0));
  AND2XL g18(.A (d), .B (s), .Y (y1));
endmodule

